name: zDevops
description: | 
    Plateforme zDevOps de Metaware .
version: v1  
category: DevOps
Description of the Catalog Entry version: 1 
Version of the Catalog to be used category: 0 
Category to be used for searching catalog entries maintainer: zDevOps 
maintainer: ymourai <ymourai@metaware.fr>
projectURL: https://github.com/youness91/zDevOps.git
