name: zDevops
description: | 
    Plateforme zDevOps .
version: v1.4.0 .   
Description of the Catalog Entry version: 0 .
Version of the Catalog to be used category: 0 .
Category to be used for searching catalog entries maintainer: zDevOps 
The maintainer of the catalog entry license: ymourai 
A URL related to the catalog entry: https://github.com/youness91/zDevOps.git
